//Max Lewis
//This program calculates the area and circumference of a circle of random radius
import java.util.Random;
import java.lang.Math.*;
/**
 * This class calculates the circumference and area of a random radius generated by the Random function
 * @author Max Lewis 
 *
 */
public class CircleCalc {
	/**
	 * This function computes the circumference, taking in the radius
	 * @param a is the radius
	 * @return the circumference 
	 */
	public static double computeCircumference(double a) {
		double total = 2 * Math.PI * a;
		return total;
	}
	/**
	 * This function computes the area of a circle, taking in the radius 
	 * @param a is the radius
	 * @return the area 
	 */
	public static double computeArea(double a) {
		double total = (a * a) * Math.PI;
		return total;
	}
	public static void main(String[] args){
		Random rnd = new Random();
		double radius = rnd.nextInt(100);
		double circ = computeCircumference(radius);
		double area = computeArea(radius);
		System.out.printf("The circumference is %.3f, and area is %.3f. The circle has a radius of %.1f.", circ, area, radius);
	}
}

